#!/usr/bin/env bun
/**
 * Code-gen script: reads weather SVGs from assets/ (BW) and assets/color/ (color),
 * plus UI icons (sunrise, sunset, quote, smile, medicine), and writes
 * public/weather-icons.ts with inline SVG strings + lookup functions.
 *
 * Run via: bun scripts/gen-icons.ts
 */

import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ASSETS = join(ROOT, "assets");
const ASSETS_COLOR = join(ROOT, "assets", "color");
const OUT = join(ROOT, "public", "weather-icons.ts");

/** Weather icons — BW and color share the same filenames. */
const WEATHER_ICONS: Record<string, string> = {
  clear: "clear.svg",
  mainlyClear: "mainly_clear.svg",
  partlyCloudy: "partly_cloudy.svg",
  overcast: "overcast.svg",
  fog: "fog.svg",
  lightning: "lightning.svg",
  rain: "rain.svg",
  rainShowers: "rain_showers.svg",
  snow: "snow.svg",
  thunderstorm: "thunderstorm.svg",
  tornado: "tornado.svg",
  unknown: "unknown.svg",
};

/**
 * UI icons used directly in dashboard components (not via the condition lookup).
 * key → filename in both assets/ (BW) and assets/color/ (color).
 */
const UI_ICONS: Record<string, { file: string; size: number }> = {
  sunrise: { file: "sunrise.svg", size: 14 },
  sunset: { file: "sunset.svg", size: 14 },
  quote: { file: "quote.svg", size: 22 },
  smile: { file: "smile.svg", size: 22 },
  medicine: { file: "medicine.svg", size: 22 },
};

// Condition string (from fetchers/weather.ts) → icon key
const CONDITION_MAP: Record<string, string> = {
  Clear: "clear",
  "Mainly Clear": "mainlyClear",
  "Partly Cloudy": "partlyCloudy",
  Overcast: "overcast",
  Fog: "fog",
  Lightning: "lightning",
  Drizzle: "rain",
  Rain: "rain",
  "Rain Showers": "rainShowers",
  Snow: "snow",
  "Snow Grains": "snow",
  "Snow Showers": "snow",
  Thunderstorm: "thunderstorm",
  Tornado: "tornado",
};

/** BW: force fill="currentColor" so CSS color cascades through. */
function patchSvgBW(raw: string, size: number): string {
  return raw
    .replace(/<svg([^>]*)>/, (_, attrs) => {
      const cleaned = attrs
        .replace(/\s*width="[^"]*"/g, "")
        .replace(/\s*height="[^"]*"/g, "")
        .replace(/\s*fill="[^"]*"/g, "");
      return `<svg${cleaned} width="${size}" height="${size}" fill="currentColor">`;
    })
    .trim();
}

/**
 * Color: keep per-path fills in the SVG source intact.
 * Only strip the top-level fill attribute so it doesn't override child fills.
 */
function patchSvgColor(raw: string, size: number): string {
  return raw
    .replace(/<svg([^>]*)>/, (_, attrs) => {
      const cleaned = attrs
        .replace(/\s*width="[^"]*"/g, "")
        .replace(/\s*height="[^"]*"/g, "")
        .replace(/\s*fill="[^"]*"/g, "");
      return `<svg${cleaned} width="${size}" height="${size}">`;
    })
    .trim();
}

let out = `// AUTO-GENERATED by scripts/gen-icons.ts — do not edit by hand\n\n`;

// ── BW weather icons ──────────────────────────────────────────────────────────
out += `// BW weather icons (fill="currentColor")\n`;
for (const [key, file] of Object.entries(WEATHER_ICONS)) {
  const raw = readFileSync(join(ASSETS, file), "utf8");
  out += `const ${key}Svg = \`${patchSvgBW(raw, 26)}\`;\n\n`;
}

// ── Color weather icons ───────────────────────────────────────────────────────
out += `// Color weather icons (per-path fills from assets/color/)\n`;
for (const [key, file] of Object.entries(WEATHER_ICONS)) {
  const raw = readFileSync(join(ASSETS_COLOR, file), "utf8");
  out += `const ${key}ColorSvg = \`${patchSvgColor(raw, 26)}\`;\n\n`;
}

// ── BW UI icons ───────────────────────────────────────────────────────────────
out += `// BW UI icons (fill="currentColor")\n`;
for (const [key, { file, size }] of Object.entries(UI_ICONS)) {
  const raw = readFileSync(join(ASSETS, file), "utf8");
  out += `export const SVG_${key.toUpperCase()}_BW = \`${patchSvgBW(raw, size)}\`;\n`;
}
out += `\n`;

// ── Color UI icons ────────────────────────────────────────────────────────────
out += `// Color UI icons (per-path fills from assets/color/)\n`;
for (const [key, { file, size }] of Object.entries(UI_ICONS)) {
  const raw = readFileSync(join(ASSETS_COLOR, file), "utf8");
  out += `export const SVG_${key.toUpperCase()}_COLOR = \`${patchSvgColor(raw, size)}\`;\n`;
}
out += `\n`;

// ── Lookup functions ──────────────────────────────────────────────────────────
out += `const CONDITION_SVGS: Record<string, string> = {\n`;
for (const [condition, key] of Object.entries(CONDITION_MAP)) {
  out += `  ${JSON.stringify(condition)}: ${key}Svg,\n`;
}
out += `};\n\n`;

out += `const CONDITION_COLOR_SVGS: Record<string, string> = {\n`;
for (const [condition, key] of Object.entries(CONDITION_MAP)) {
  out += `  ${JSON.stringify(condition)}: ${key}ColorSvg,\n`;
}
out += `};\n\n`;

out += `export function getWeatherIcon(condition: string): string {\n`;
out += `  return CONDITION_SVGS[condition] ?? unknownSvg;\n`;
out += `}\n\n`;

out += `export function getWeatherIconColor(condition: string): string {\n`;
out += `  return CONDITION_COLOR_SVGS[condition] ?? unknownColorSvg;\n`;
out += `}\n`;

writeFileSync(OUT, out, "utf8");
console.log(`Written: ${OUT}`);
